<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find slambot_description)/urdf/common_properties.urdf.xacro"/>

  <!-- Caster board -->
  <xacro:property name="caster_board_x" value="0.060" />
  <xacro:property name="caster_board_y" value="${body_y}" />
  <xacro:property name="caster_board_z" value="0.003" />

  <xacro:property name="sphere_radius" value="0.012" />

  <xacro:property name="velocity_scale_factor" value="1.0"/>
  <xacro:macro name="caster_board" params="prefix parent *joint_origin *joint_axis">

  <!-- Front caster_board -->
  <joint name="${prefix}_caster_board_joint" type="fixed">
    <xacro:insert_block name="joint_origin"/>
    <xacro:insert_block name="joint_axis"/>
    <parent link="${parent}"/>
    <child link="${prefix}_caster_board"/>
    <origin xyz="0 0 0"
            rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="${prefix}_caster_board">
    <visual>
      <geometry>
        <box size="${caster_board_x} ${caster_board_y} ${caster_board_z}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${caster_board_x} ${caster_board_y} ${caster_board_z}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.0020833333" ixy="0" ixz="0" iyy="0.0070833333" iyz="0" izz="0.0083333333"/>
    </inertial>
  </link>

  <!-- Caster -->
  <joint name="${prefix}_caster_joint" type="fixed">
    <parent link="${prefix}_caster_board"/>
    <child link="${prefix}_caster"/>
    <origin xyz="0 0 -${sphere_radius}"/>
  </joint>

  <link name="${prefix}_caster">
    <visual>
      <origin xyz="0 0 -${caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -${caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 -${caster_board_z/2}"
              rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.0020833333" ixy="0" ixz="0" iyy="0.0070833333" iyz="0" izz="0.0083333333"/>
    </inertial>
  </link>
 
  <!-- Spacer_1 -->
  <joint name="${prefix}_spacer_joint_1" type="fixed">
    <parent link="${prefix}_caster_board"/>
    <child link="${prefix}_spacer_1"/>
    <origin xyz="${caster_board_x/2} ${caster_board_y/2} 0"
            rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="${prefix}_spacer_1">
    <visual>
      <origin xyz="-${spacer_rud27} -${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-${spacer_rud27} -${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.5"/>
      <mass value="0.1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Spacer_2 -->
  <joint name="${prefix}_spacer_joint_2" type="fixed">
    <parent link="${prefix}_caster_board"/>
    <child link="${prefix}_spacer_2"/>
    <origin xyz="${caster_board_x/2} -${caster_board_y/2} 0"
            rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="${prefix}_spacer_2">
    <visual>
      <origin xyz="-${spacer_rud27} ${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-${spacer_rud27} ${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.5"/>
      <mass value="0.1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Spacer_3 -->
  <joint name="${prefix}_spacer_joint_3" type="fixed">
    <parent link="${prefix}_caster_board"/>
    <child link="${prefix}_spacer_3"/>
    <origin xyz="-${caster_board_x/2} ${caster_board_y/2} 0"
            rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="${prefix}_spacer_3">
    <visual>
      <origin xyz="${spacer_rud27} -${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${spacer_rud27} -${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.5"/>
      <mass value="0.1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Spacer_4 -->
  <joint name="${prefix}_spacer_joint_4" type="fixed">
    <parent link="${prefix}_caster_board"/>
    <child link="${prefix}_spacer_4"/>
    <origin xyz="-${caster_board_x/2} -${caster_board_y/2} 0"
            rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
  </joint>

  <link name="${prefix}_spacer_4">
    <visual>
      <origin xyz="${spacer_rud27} ${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${spacer_rud27} ${spacer_rud27} ${spacer_len27/2 + caster_board_z/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${spacer_len27}" radius="${spacer_rud27}"/>
      </geometry>
    </collision>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0.5"/>
      <mass value="0.1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>


  </xacro:macro> 
</robot>

