<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find slambot_description)/urdf/common_properties.urdf.xacro"/>

  <xacro:macro name="spacer" params="prefix suffix len rad parent *joint_origin *joint_axis">

  <joint name="${prefix}_spacer_${suffix}_joint" type="fixed">
    <xacro:insert_block name="joint_origin"/>
    <xacro:insert_block name="joint_axis"/>
    <parent link="${parent}"/>
    <child link="${prefix}_spacer_${suffix}"/>
  </joint>

  <link name="${prefix}_spacer_${suffix}">
    <visual>
      <origin xyz="0 0 ${len/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${len}" radius="${rad}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${len/2}"
              rpy="0 0 0"/>
      <geometry>
        <cylinder length="${len}" radius="${rad}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${len/2}"
              rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  </xacro:macro> 

</robot>
